check_vignettes <- function(package_directory){
  vignettes <- "No vignettes"
  files <- list.files(file.path(package_directory, "vignettes"))
  if(length(files) == 0){
    return(vignettes)
  }
  
  if(grepl(x = files, pattern = "\\.Rnw$")){
    vignettes <- "Sweave"
  } else if(grepl(x = files, pattern = "\\.Rmd")){
    vignettes <- "Knitr"
  }
  return(vignettes)

}

#'@title check whether a package's documentation uses roxygen2
#'@description identifies if a package's documentation uses
#'roxygen2's inline documentation, by scanning the R files
#'hunting for roxygen2 tags.
#'
#'@param package_directory the full path to the directory, retrieved
#'with \code{\link{get_package_source}}.
#'
#'@details checking for roxygen2 is fairly simple. One way is to
#'look at the ./man files and search for the "% Generated by roxygen2"
#'tag, but early versions of roxygen2 didn't introduce that tag.
#'Instead, we scan the .R files hunting for actual tags, specifically
#'searching for @@export (which every package, presumably, must have
#'at least once - there wouldn't actually be any R it provides if
#'not.)
#'
#'@return either TRUE or FALSE, depending on whether or not
#'roxygen2 tags are found in the source code.
#'
#'@examples
#'#Identify if ggplot2 uses roxygen
#'file_location <- get_package_source("ggplot2")
#'check_roxygen(file_location)
#'remove_package_source(file_location)
#'
#'@export
check_roxygen <- function(package_directory){
  check_content(package_directory, "@export")
}

#'@title identify if a package is semantically versioned
#'@description take a package's metadata and identify
#'from it whether the package follows the "semantic versioning"
#'convention, at least in theory. See details for, well,
#'details.
#'
#'@details \href{http://semver.org/}{semantic versioning}
#'is a convention for identifying version numbers of a codebase
#'in a way that distinguishes major changes, minor changes
#'and patches by using three period-separated
#'groups of digits. As an example, 2.0.0 is semantically
#'versioned; 2.0 is not.
#'
#'@param package_metadata package metadata retrieved with \code{\link{get_package_metadata}}.
#'
#'@return TRUE if the package does follow the semantic versioning standard,
#'FALSE if not.
#'
#'@examples
#'#Identify if ggplot2 is semantically versioned (it is)
#'ggplot_metadata <- get_package_metadata("ggplot2")
#'check_versioning(ggplot_metadata)
#'
#'#Identify if A3 is semantically versioned (it isn't)
#'@export
check_versioning <- function(package_metadata){
  grepl(x = package_metadata$latest, pattern = "\\d{1,}\\.\\d{1,}\\.\\d{1,}")
}

check_changelog <- function(package_metadata){
  
}