check_vignettes <- function(package_directory){
  vignettes <- "No vignettes"
  files <- list.files(file.path(package_directory, "vignettes"))
  if(length(files) == 0){
    return(vignettes)
  }
  
  if(grepl(x = files, pattern = "\\.Rnw$")){
    vignettes <- "Sweave"
  } else if(grepl(x = files, pattern = "\\.Rmd")){
    vignettes <- "Knitr"
  }
  return(vignettes)

}

#'@title check whether a package's documentation uses roxygen2
#'@description identifies if a package's documentation uses
#'roxygen2's inline documentation, by scanning the R files
#'hunting for roxygen2 tags.
#'
#'@param package_directory the full path to the directory, retrieved
#'with \code{\link{get_package_source}}.
#'
#'@details checking for roxygen2 is fairly simple. One way is to
#'look at the ./man files and search for the "% Generated by roxygen2"
#'tag, but early versions of roxygen2 didn't introduce that tag.
#'Instead, we scan the .R files hunting for actual tags, specifically
#'searching for @@export (which every package, presumably, must have
#'at least once - there wouldn't actually be any R it provides if
#'not.)
#'
#'@examples
#'#Identify if ggplot2 uses roxygen
#'file_location <- get_package_source("ggplot2")
#'check_roxygen(file_location)
#'remove_package_source(file_location)
#'
#'@export
check_roxygen <- function(package_directory){
  check_content(package_directory, "@export")
}

check_versioning <- function(package_metadata){
  
}

check_changelog <- function(package_metadata){
  
}